# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1875d066a33678164d06aaab0e56ae9c71571f0af4be0e2d964acf146d99c2f3dc91d0fb12d564bcb5541fc1ae595ca8e06cb6b9ecea6f4e81d2b4fc523f1683

test:
  secret_key_base: 8f0775e9c46b18ab0e762483da6c6df260601eaa91967ff4447cc88a2e4fecae4221f1ebf753be7b96f2529892084a6e6d4ebc79e9511af56c2243035ddd5f9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
